export const areas = [
  {
    area: "America",
    locations: [
      "Adak",
      "Anchorage",
      "Araguaina",
      "Argentina/Buenos Aires",
      "Argentina/Catamarca",
      "Argentina/Cordoba",
      "Argentina/Jujuy",
      "Argentina/La Rioja",
      "Argentina/Mendoza",
      "Argentina/Rio Gallegos",
      "Argentina/Salta",
      "Argentina/San Juan",
      "Argentina/San Luis",
      "Argentina/Tucuman",
      "Argentina/Ushuaia",
      "Asuncion",
      "Atikokan",
      "Bahia",
      "Bahia Banderas",
      "Barbados",
      "Belem",
      "Belize",
      "Blanc-Sablon",
      "Boa Vista",
      "Bogota",
      "Boise",
      "Cambridge Bay",
      "Campo Grande",
      "Cancun",
      "Caracas",
      "Cayenne",
      "Chicago",
      "Chihuahua",
      "Costa Rica",
      "Creston",
      "Cuiaba",
      "Curacao",
      "Danmarkshavn",
      "Dawson",
      "Dawson Creek",
      "Denver",
      "Detroit",
      "Edmonton",
      "Eirunepe",
      "El Salvador",
      "Fort Nelson",
      "Fortaleza",
      "Glace Bay",
      "Goose Bay",
      "Grand Turk",
      "Guatemala",
      "Guayaquil",
      "Guyana",
      "Halifax",
      "Havana",
      "Hermosillo",
      "Indiana/Indianapolis",
      "Indiana/Knox",
      "Indiana/Marengo",
      "Indiana/Petersburg",
      "Indiana/Tell City",
      "Indiana/Vevay",
      "Indiana/Vincennes",
      "Indiana/Winamac",
      "Inuvik",
      "Iqaluit",
      "Jamaica",
      "Juneau",
      "Kentucky/Louisville",
      "Kentucky/Monticello",
      "La Paz",
      "Lima",
      "Los Angeles",
      "Maceio",
      "Managua",
      "Manaus",
      "Martinique",
      "Matamoros",
      "Mazatlan",
      "Menominee",
      "Merida",
      "Metlakatla",
      "Mexico City",
      "Miquelon",
      "Moncton",
      "Monterrey",
      "Montevideo",
      "Nassau",
      "New York",
      "Nipigon",
      "Nome",
      "Noronha",
      "North Dakota/Beulah",
      "North Dakota/Center",
      "North Dakota/New Salem",
      "Nuuk",
      "Ojinaga",
      "Panama",
      "Pangnirtung",
      "Paramaribo",
      "Phoenix",
      "Port-au-Prince",
      "Port of Spain",
      "Porto Velho",
      "Puerto Rico",
      "Punta Arenas",
      "Rainy River",
      "Rankin Inlet",
      "Recife",
      "Regina",
      "Resolute",
      "Rio Branco",
      "Santarem",
      "Santiago",
      "Santo Domingo",
      "Sao Paulo",
      "Scoresbysund",
      "Sitka",
      "St Johns",
      "Swift Current",
      "Tegucigalpa",
      "Thule",
      "Thunder Bay",
      "Tijuana",
      "Toronto",
      "Vancouver",
      "Whitehorse",
      "Winnipeg",
      "Yakutat",
      "Yellowknife",
    ],
  },
  {
    area: "Africa",
    locations: [
      "Abidjan",
      "Accra",
      "Algiers",
      "Bissau",
      "Cairo",
      "Casablanca",
      "Ceuta",
      "El Aaiun",
      "Johannesburg",
      "Juba",
      "Khartoum",
      "Lagos",
      "Maputo",
      "Monrovia",
      "Nairobi",
      "Ndjamena",
      "Sao Tome",
      "Tripoli",
      "Tunis",
      "Windhoek",
    ],
  },
  {
    area: "Antarctica",
    locations: [
      "Casey",
      "Davis",
      "DumontDUrville",
      "Macquarie",
      "Mawson",
      "Palmer",
      "Rothera",
      "Syowa",
      "Troll",
      "Vostok",
    ],
  },
  {
    area: "Asia",
    locations: [
      "Almaty",
      "Amman",
      "Anadyr",
      "Aqtau",
      "Aqtobe",
      "Ashgabat",
      "Atyrau",
      "Baghdad",
      "Baku",
      "Bangkok",
      "Barnaul",
      "Beirut",
      "Bishkek",
      "Brunei",
      "Chita",
      "Choibalsan",
      "Colombo",
      "Damascus",
      "Dhaka",
      "Dili",
      "Dubai",
      "Dushanbe",
      "Famagusta",
      "Gaza",
      "Hebron",
      "Ho Chi Minh",
      "Hong Kong",
      "Hovd",
      "Irkutsk",
      "Jakarta",
      "Jayapura",
      "Jerusalem",
      "Kabul",
      "Kamchatka",
      "Karachi",
      "Kathmandu",
      "Khandyga",
      "Kolkata",
      "Krasnoyarsk",
      "Kuala Lumpur",
      "Kuching",
      "Macau",
      "Magadan",
      "Makassar",
      "Manila",
      "Nicosia",
      "Novokuznetsk",
      "Novosibirsk",
      "Omsk",
      "Oral",
      "Pontianak",
      "Pyongyang",
      "Qatar",
      "Qostanay",
      "Qyzylorda",
      "Riyadh",
      "Sakhalin",
      "Samarkand",
      "Seoul",
      "Shanghai",
      "Singapore",
      "Srednekolymsk",
      "Taipei",
      "Tashkent",
      "Tbilisi",
      "Tehran",
      "Thimphu",
      "Tokyo",
      "Tomsk",
      "Ulaanbaatar",
      "Urumqi",
      "Ust-Nera",
      "Vladivostok",
      "Yakutsk",
      "Yangon",
      "Yekaterinburg",
      "Yerevan",
    ],
  },
  {
    area: "Atlantic",
    locations: [
      "Azores",
      "Bermuda",
      "Canary",
      "Cape Verde",
      "Faroe",
      "Madeira",
      "Reykjavik",
      "South Georgia",
      "Stanley",
    ],
  },
  {
    area: "Australia",
    locations: [
      "Adelaide",
      "Brisbane",
      "Broken Hill",
      "Darwin",
      "Eucla",
      "Hobart",
      "Lindeman",
      "Lord Howe",
      "Melbourne",
      "Perth",
      "Sydney",
    ],
  },
  {
    area: "Europe",
    locations: [
      "Amsterdam",
      "Andorra",
      "Astrakhan",
      "Athens",
      "Belgrade",
      "Berlin",
      "Brussels",
      "Bucharest",
      "Budapest",
      "Chisinau",
      "Copenhagen",
      "Dublin",
      "Gibraltar",
      "Helsinki",
      "Istanbul",
      "Kaliningrad",
      "Kiev",
      "Kirov",
      "Lisbon",
      "London",
      "Luxembourg",
      "Madrid",
      "Malta",
      "Minsk",
      "Monaco",
      "Moscow",
      "Oslo",
      "Paris",
      "Prague",
      "Riga",
      "Rome",
      "Samara",
      "Saratov",
      "Simferopol",
      "Sofia",
      "Stockholm",
      "Tallinn",
      "Tirane",
      "Ulyanovsk",
      "Uzhgorod",
      "Vienna",
      "Vilnius",
      "Volgograd",
      "Warsaw",
      "Zaporozhye",
      "Zurich",
    ],
  },
  {
    area: "Indian",
    locations: [
      "Chagos",
      "Christmas",
      "Cocos",
      "Kerguelen",
      "Mahe",
      "Maldives",
      "Mauritius",
      "Reunion",
    ],
  },
  {
    area: "Pacific",
    locations: [
      "Apia",
      "Auckland",
      "Bougainville",
      "Chatham",
      "Chuuk",
      "Easter",
      "Efate",
      "Enderbury",
      "Fakaofo",
      "Fiji",
      "Funafuti",
      "Galapagos",
      "Gambier",
      "Guadalcanal",
      "Guam",
      "Honolulu",
      "Kiritimati",
      "Kosrae",
      "Kwajalein",
      "Majuro",
      "Marquesas",
      "Nauru",
      "Niue",
      "Norfolk",
      "Noumea",
      "Pago Pago",
      "Palau",
      "Pitcairn",
      "Pohnpei",
      "Port Moresby",
      "Rarotonga",
      "Tahiti",
      "Tarawa",
      "Tongatapu",
      "Wake",
      "Wallis",
    ],
  },
];
